
project_id = "llxzstqejdrplmxdjxlu"

[functions.stripe-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.upload-founder-images]
verify_jwt = false

[functions.submit-article]
verify_jwt = false

[functions.notify-submission]
verify_jwt = false

